### ISSUE TITLE
Mediapart Calibre recipe not fetching anymore

### ISSUE THREAD

**Issue by ctesiphon** [lhoupert/calibre_contrib#1]
@lhoupert :

Hi Loïc,

Your Mediapart Calibre "recipe" is nearly perfect, and I enjoyed it for some time, but since a few days, the recipe is not fetching news anymore. It only captures the heads of the news, without any content.

It seems that it is related to the recent update of the website. It may have happened nov. 21, because I can see in Calibre that the size of the epubs has drastically gone down since last sunday (see screen capture below).

Could you please update your code ? I wanted to do it by myself, but I failed to understand the official guide, on Calibre's website (https://manual.calibre-ebook.com/fr/news.html), and I do not want to break the code even more.

Thank you very much.

![Capture d’écran 2021-11-27 à 19 36 02](https://user-images.githubusercontent.com/5954933/143719308-19aa5ff1-d60d-4fc5-b898-b36625aa6be4.png)

**Comment by lhoupert** [comment]
Sorry @ctesiphon, I am only seeing your message today. Mediapart changes regularly the way they structure their articles data on their webpage. It would take a lot of time to change the recipe to adapt it to the current version of the website and unfortunately I dont have the time for that sorry, and even if I change the recipe, the same may occur again in a couple of months.

My advices would be to email https://github.com/mediapart and ask them :
1) if they are planning to propose an epub version of their articles,
2) if they could make available an API for subscribers so we could access the articles metadata 

I may reconsider spending some time to develop this recipe if I know the articles metadata is properly documented.
